import {
    imgBack, 
    imgAsCopas, 
    img2copas, 
    img3copas, 
    img4copas, 
    img5copas, 
    img6copas, 
    img7copas, 
    imgSotacopas, 
    imgCabcopas, 
    imgReycopas,
    puntaje,
    setPuntaje,
    intentos,
    setIntentos,
    spanPuntos,
    spanIntentos,
    imgCarta,
    divCartas,
    btnDameCarta,
    btnMePlanto
} from "./modelo.js"
